/*
 * Kanbanize API v2
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@kanbanize.com
 * Generated by: https://openapi-generator.tech
 */

/// AddCardTemplateCardRelatedCard200ResponseData : The position of the related card within the card's list of linked cards.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AddCardTemplateCardRelatedCard200ResponseData {
    #[serde(rename = "position", skip_serializing_if = "Option::is_none")]
    pub position: Option<i32>,
}

impl AddCardTemplateCardRelatedCard200ResponseData {
    /// The position of the related card within the card's list of linked cards.
    pub fn new() -> AddCardTemplateCardRelatedCard200ResponseData {
        AddCardTemplateCardRelatedCard200ResponseData {
            position: None,
        }
    }
}


