/*
 * Kanbanize API v2
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@kanbanize.com
 * Generated by: https://openapi-generator.tech
 */

/// AddFavoriteBoard200ResponseData : The position of the board within the list of your favorite boards.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AddFavoriteBoard200ResponseData {
    #[serde(rename = "position", skip_serializing_if = "Option::is_none")]
    pub position: Option<i32>,
}

impl AddFavoriteBoard200ResponseData {
    /// The position of the board within the list of your favorite boards.
    pub fn new() -> AddFavoriteBoard200ResponseData {
        AddFavoriteBoard200ResponseData {
            position: None,
        }
    }
}


