/*
 * Kanbanize API v2
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@kanbanize.com
 * Generated by: https://openapi-generator.tech
 */

/// AddCardTemplateCardPredecessorCardRequest : Link data.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AddCardTemplateCardPredecessorCardRequest {
    /// The position of the predecessor card within the successor's list of linked cards.
    #[serde(rename = "linked_card_position", skip_serializing_if = "Option::is_none")]
    pub linked_card_position: Option<i32>,
    /// The position of the successor card within the predecessor's list of linked cards.
    #[serde(rename = "card_position", skip_serializing_if = "Option::is_none")]
    pub card_position: Option<i32>,
}

impl AddCardTemplateCardPredecessorCardRequest {
    /// Link data.
    pub fn new() -> AddCardTemplateCardPredecessorCardRequest {
        AddCardTemplateCardPredecessorCardRequest {
            linked_card_position: None,
            card_position: None,
        }
    }
}


