/*
 * Kanbanize API v2
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@kanbanize.com
 * Generated by: https://openapi-generator.tech
 */

/// AddChildCardRequest : Link data.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AddChildCardRequest {
    /// The position of the child card within the parent's list of linked cards.
    #[serde(rename = "linked_card_position", skip_serializing_if = "Option::is_none")]
    pub linked_card_position: Option<i32>,
    /// The position of the parent card within the child's list of linked cards.
    #[serde(rename = "card_position", skip_serializing_if = "Option::is_none")]
    pub card_position: Option<i32>,
    /// Exceeding reason data.
    #[serde(rename = "exceeding_reason", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub exceeding_reason: Option<Option<String>>,
}

impl AddChildCardRequest {
    /// Link data.
    pub fn new() -> AddChildCardRequest {
        AddChildCardRequest {
            linked_card_position: None,
            card_position: None,
            exceeding_reason: None,
        }
    }
}


