/*
 * Kanbanize API v2
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@kanbanize.com
 * Generated by: https://openapi-generator.tech
 */

/// ApiLimit : An hourly or minutely api request limit.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiLimit {
    #[serde(rename = "types", skip_serializing_if = "Option::is_none")]
    pub types: Option<String>,
    #[serde(rename = "limit", skip_serializing_if = "Option::is_none")]
    pub limit: Option<i32>,
}

impl ApiLimit {
    /// An hourly or minutely api request limit.
    pub fn new() -> ApiLimit {
        ApiLimit {
            types: None,
            limit: None,
        }
    }
}


