/*
 * Kanbanize API v2
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@kanbanize.com
 * Generated by: https://openapi-generator.tech
 */

/// BusinessRulesExecutionHistoryEvent : An event recorded for each business rules execution



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct BusinessRulesExecutionHistoryEvent {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(rename = "business_rule_id", skip_serializing_if = "Option::is_none")]
    pub business_rule_id: Option<i32>,
    #[serde(rename = "business_rule_name", skip_serializing_if = "Option::is_none")]
    pub business_rule_name: Option<String>,
    #[serde(rename = "executed_on_card_id", skip_serializing_if = "Option::is_none")]
    pub executed_on_card_id: Option<i32>,
    #[serde(rename = "executed_at", skip_serializing_if = "Option::is_none")]
    pub executed_at: Option<String>,
}

impl BusinessRulesExecutionHistoryEvent {
    /// An event recorded for each business rules execution
    pub fn new() -> BusinessRulesExecutionHistoryEvent {
        BusinessRulesExecutionHistoryEvent {
            id: None,
            business_rule_id: None,
            business_rule_name: None,
            executed_on_card_id: None,
            executed_at: None,
        }
    }
}


