/*
 * Kanbanize API v2
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@kanbanize.com
 * Generated by: https://openapi-generator.tech
 */

/// CardBlockReasonSetRequest : Card block reason data.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CardBlockReasonSetRequest {
    /// The reason id of the block reason.
    #[serde(rename = "reason_id", skip_serializing_if = "Option::is_none")]
    pub reason_id: Option<i32>,
    /// The comment of the block reason.
    #[serde(rename = "comment", skip_serializing_if = "Option::is_none")]
    pub comment: Option<String>,
    /// A list of user ids.
    #[serde(rename = "users", skip_serializing_if = "Option::is_none")]
    pub users: Option<Vec<i32>>,
    /// Date.
    #[serde(rename = "date", skip_serializing_if = "Option::is_none")]
    pub date: Option<String>,
    /// A list of card ids.
    #[serde(rename = "cards", skip_serializing_if = "Option::is_none")]
    pub cards: Option<Vec<i32>>,
}

impl CardBlockReasonSetRequest {
    /// Card block reason data.
    pub fn new() -> CardBlockReasonSetRequest {
        CardBlockReasonSetRequest {
            reason_id: None,
            comment: None,
            users: None,
            date: None,
            cards: None,
        }
    }
}


