/*
 * Kanbanize API v2
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@kanbanize.com
 * Generated by: https://openapi-generator.tech
 */

/// CardTemplateCustomFieldDataDropdown : Card template custom field data - dropdown



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CardTemplateCustomFieldDataDropdown {
    #[serde(rename = "values", skip_serializing_if = "Option::is_none")]
    pub values: Option<Vec<crate::models::CardTemplateCustomFieldDataDropdownValuesInner>>,
}

impl CardTemplateCustomFieldDataDropdown {
    /// Card template custom field data - dropdown
    pub fn new() -> CardTemplateCustomFieldDataDropdown {
        CardTemplateCustomFieldDataDropdown {
            values: None,
        }
    }
}


