/*
 * Kanbanize API v2
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@kanbanize.com
 * Generated by: https://openapi-generator.tech
 */

/// CardTemplateStickerAddRequest : Card template stricker data.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CardTemplateStickerAddRequest {
    /// The sticker id of the sticker.
    #[serde(rename = "sticker_id")]
    pub sticker_id: i32,
}

impl CardTemplateStickerAddRequest {
    /// Card template stricker data.
    pub fn new(sticker_id: i32) -> CardTemplateStickerAddRequest {
        CardTemplateStickerAddRequest {
            sticker_id,
        }
    }
}


