/*
 * Kanbanize API v2
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@kanbanize.com
 * Generated by: https://openapi-generator.tech
 */

/// CardTemplateCustomFieldAddOrUpdateRequest : Card template custom field data.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CardTemplateCustomFieldAddOrUpdateRequest {
    /// The value of custom field.
    #[serde(rename = "value", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub value: Option<Option<String>>,
    /// A list of selected values to add or update.
    #[serde(rename = "selected_values_to_add_or_update", skip_serializing_if = "Option::is_none")]
    pub selected_values_to_add_or_update: Option<Vec<crate::models::CardTemplateCustomFieldSelectedValueAddOrUpdateRequest>>,
    /// A list of selected values to remove.
    #[serde(rename = "selected_value_ids_to_remove", skip_serializing_if = "Option::is_none")]
    pub selected_value_ids_to_remove: Option<Vec<i32>>,
    /// The other value of custom field.
    #[serde(rename = "other_value", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub other_value: Option<Option<String>>,
    /// The contributor ids which will be added to card template custom field.
    #[serde(rename = "contributor_ids_to_add", skip_serializing_if = "Option::is_none")]
    pub contributor_ids_to_add: Option<Vec<i32>>,
    /// The contributor ids which will be removed from card template custom field.
    #[serde(rename = "contributor_ids_to_remove", skip_serializing_if = "Option::is_none")]
    pub contributor_ids_to_remove: Option<Vec<i32>>,
    /// A list of files to add.
    #[serde(rename = "files_to_add", skip_serializing_if = "Option::is_none")]
    pub files_to_add: Option<Vec<crate::models::CardTemplateCustomFieldFileCreateRequest>>,
    /// A list of files to update.
    #[serde(rename = "files_to_update", skip_serializing_if = "Option::is_none")]
    pub files_to_update: Option<Vec<crate::models::CardTemplateCustomFieldFileUpdateRequest>>,
    /// A list of file ids to remove.
    #[serde(rename = "file_ids_to_remove", skip_serializing_if = "Option::is_none")]
    pub file_ids_to_remove: Option<Vec<i32>>,
}

impl CardTemplateCustomFieldAddOrUpdateRequest {
    /// Card template custom field data.
    pub fn new() -> CardTemplateCustomFieldAddOrUpdateRequest {
        CardTemplateCustomFieldAddOrUpdateRequest {
            value: None,
            selected_values_to_add_or_update: None,
            selected_value_ids_to_remove: None,
            other_value: None,
            contributor_ids_to_add: None,
            contributor_ids_to_remove: None,
            files_to_add: None,
            files_to_update: None,
            file_ids_to_remove: None,
        }
    }
}


