/*
 * Kanbanize API v2
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@kanbanize.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CardTemplateCustomFieldCreateOrUpdateRequestContributorContributorsInner {
    /// The user id of the contributor.
    #[serde(rename = "user_id", skip_serializing_if = "Option::is_none")]
    pub user_id: Option<i32>,
}

impl CardTemplateCustomFieldCreateOrUpdateRequestContributorContributorsInner {
    pub fn new() -> CardTemplateCustomFieldCreateOrUpdateRequestContributorContributorsInner {
        CardTemplateCustomFieldCreateOrUpdateRequestContributorContributorsInner {
            user_id: None,
        }
    }
}


