/*
 * Kanbanize API v2
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@kanbanize.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CardTemplateCustomFieldDataDropdownValuesInner {
    #[serde(rename = "value_id", skip_serializing_if = "Option::is_none")]
    pub value_id: Option<i32>,
    #[serde(rename = "position", skip_serializing_if = "Option::is_none")]
    pub position: Option<i32>,
}

impl CardTemplateCustomFieldDataDropdownValuesInner {
    pub fn new() -> CardTemplateCustomFieldDataDropdownValuesInner {
        CardTemplateCustomFieldDataDropdownValuesInner {
            value_id: None,
            position: None,
        }
    }
}


