/*
 * Kanbanize API v2
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@kanbanize.com
 * Generated by: https://openapi-generator.tech
 */

/// CardCustomFieldDataCardPicker : Card custom field data - card picker



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CardCustomFieldDataCardPicker {
    #[serde(rename = "selected_cards", skip_serializing_if = "Option::is_none")]
    pub selected_cards: Option<Vec<crate::models::CardCustomFieldDataCardPickerSelectedCardsInner>>,
}

impl CardCustomFieldDataCardPicker {
    /// Card custom field data - card picker
    pub fn new() -> CardCustomFieldDataCardPicker {
        CardCustomFieldDataCardPicker {
            selected_cards: None,
        }
    }
}


