/*
 * Kanbanize API v2
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@kanbanize.com
 * Generated by: https://openapi-generator.tech
 */

/// CardOutcomeCheckpointCreateRequest : Card outcome checkpoint data.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CardOutcomeCheckpointCreateRequest {
    /// Time
    #[serde(rename = "time")]
    pub time: String,
    /// The checkpoint name.
    #[serde(rename = "name")]
    pub name: String,
    /// Value
    #[serde(rename = "value")]
    pub value: f64,
}

impl CardOutcomeCheckpointCreateRequest {
    /// Card outcome checkpoint data.
    pub fn new(time: String, name: String, value: f64) -> CardOutcomeCheckpointCreateRequest {
        CardOutcomeCheckpointCreateRequest {
            time,
            name,
            value,
        }
    }
}


