/*
 * Kanbanize API v2
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@kanbanize.com
 * Generated by: https://openapi-generator.tech
 */

/// CardOutcomeValueUpdateRequest : Card outcome value data.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CardOutcomeValueUpdateRequest {
    /// Value
    #[serde(rename = "value", skip_serializing_if = "Option::is_none")]
    pub value: Option<f64>,
    #[serde(rename = "time", skip_serializing_if = "Option::is_none")]
    pub time: Option<String>,
}

impl CardOutcomeValueUpdateRequest {
    /// Card outcome value data.
    pub fn new() -> CardOutcomeValueUpdateRequest {
        CardOutcomeValueUpdateRequest {
            value: None,
            time: None,
        }
    }
}


