/*
 * Kanbanize API v2
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@kanbanize.com
 * Generated by: https://openapi-generator.tech
 */

/// CardSticker : Card sticker data



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CardSticker {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(rename = "card_id", skip_serializing_if = "Option::is_none")]
    pub card_id: Option<i32>,
    #[serde(rename = "sticker_id", skip_serializing_if = "Option::is_none")]
    pub sticker_id: Option<i32>,
}

impl CardSticker {
    /// Card sticker data
    pub fn new() -> CardSticker {
        CardSticker {
            id: None,
            card_id: None,
            sticker_id: None,
        }
    }
}


