/*
 * Kanbanize API v2
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@kanbanize.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CardCommentRecipientsRecipients {
    #[serde(rename = "to", skip_serializing_if = "Option::is_none")]
    pub to: Option<Vec<crate::models::CardCommentAuthorAuthor>>,
    #[serde(rename = "cc", skip_serializing_if = "Option::is_none")]
    pub cc: Option<Vec<crate::models::CardCommentAuthorAuthor>>,
    #[serde(rename = "bcc", skip_serializing_if = "Option::is_none")]
    pub bcc: Option<Vec<crate::models::CardCommentAuthorAuthor>>,
}

impl CardCommentRecipientsRecipients {
    pub fn new() -> CardCommentRecipientsRecipients {
        CardCommentRecipientsRecipients {
            to: None,
            cc: None,
            bcc: None,
        }
    }
}


