/*
 * Kanbanize API v2
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@kanbanize.com
 * Generated by: https://openapi-generator.tech
 */

/// CheckSpfRecordRequest : Domain data.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CheckSpfRecordRequest {
    /// The domain name to be checked.
    #[serde(rename = "domain")]
    pub domain: String,
}

impl CheckSpfRecordRequest {
    /// Domain data.
    pub fn new(domain: String) -> CheckSpfRecordRequest {
        CheckSpfRecordRequest {
            domain,
        }
    }
}


