/*
 * Kanbanize API v2
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@kanbanize.com
 * Generated by: https://openapi-generator.tech
 */

/// CreateWorkflowRequest : Workflow data.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateWorkflowRequest {
    /// Postion of the workflow within the board.
    #[serde(rename = "position", skip_serializing_if = "Option::is_none")]
    pub position: Option<i32>,
    /// Controls whether the workflow is enabled.
    #[serde(rename = "is_enabled", skip_serializing_if = "Option::is_none")]
    pub is_enabled: Option<IsEnabled>,
    /// Controls whether the workflow is collapsible.
    #[serde(rename = "is_collapsible", skip_serializing_if = "Option::is_none")]
    pub is_collapsible: Option<IsCollapsible>,
    /// The name of the new workflow.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// The type of workflow can be 0 - cards workflow, 1 - initiatives workflow or 2 - timeline.
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<Type>,
}

impl CreateWorkflowRequest {
    /// Workflow data.
    pub fn new() -> CreateWorkflowRequest {
        CreateWorkflowRequest {
            position: None,
            is_enabled: None,
            is_collapsible: None,
            name: None,
            r#type: None,
        }
    }
}

/// Controls whether the workflow is enabled.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum IsEnabled {
    #[serde(rename = "0")]
    Variant0,
    #[serde(rename = "1")]
    Variant1,
}

impl Default for IsEnabled {
    fn default() -> IsEnabled {
        Self::Variant0
    }
}
/// Controls whether the workflow is collapsible.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum IsCollapsible {
    #[serde(rename = "0")]
    Variant0,
    #[serde(rename = "1")]
    Variant1,
}

impl Default for IsCollapsible {
    fn default() -> IsCollapsible {
        Self::Variant0
    }
}
/// The type of workflow can be 0 - cards workflow, 1 - initiatives workflow or 2 - timeline.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "0")]
    Variant0,
    #[serde(rename = "1")]
    Variant1,
    #[serde(rename = "2")]
    Variant2,
}

impl Default for Type {
    fn default() -> Type {
        Self::Variant0
    }
}

