/*
 * Kanbanize API v2
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@kanbanize.com
 * Generated by: https://openapi-generator.tech
 */

/// CreateWorkspaceRequest : Workspace data.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateWorkspaceRequest {
    /// The name of the new workspace.
    #[serde(rename = "name")]
    pub name: String,
    /// The type of the workspace: 1 - team workspace, 2 - management workspace.
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<Type>,
}

impl CreateWorkspaceRequest {
    /// Workspace data.
    pub fn new(name: String) -> CreateWorkspaceRequest {
        CreateWorkspaceRequest {
            name,
            r#type: None,
        }
    }
}

/// The type of the workspace: 1 - team workspace, 2 - management workspace.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "1")]
    Variant1,
    #[serde(rename = "2")]
    Variant2,
}

impl Default for Type {
    fn default() -> Type {
        Self::Variant1
    }
}

