/*
 * Kanbanize API v2
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@kanbanize.com
 * Generated by: https://openapi-generator.tech
 */

/// CreateArchiveCardVersionRequest : Archived card version data.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateArchiveCardVersionRequest {
    /// The name of the new version.
    #[serde(rename = "name")]
    pub name: String,
}

impl CreateArchiveCardVersionRequest {
    /// Archived card version data.
    pub fn new(name: String) -> CreateArchiveCardVersionRequest {
        CreateArchiveCardVersionRequest {
            name,
        }
    }
}


