/*
 * Kanbanize API v2
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@kanbanize.com
 * Generated by: https://openapi-generator.tech
 */

/// CreateMergedAreaRequest : Merged area data.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateMergedAreaRequest {
    /// The ids of the lanes which are a part of the merged area.
    #[serde(rename = "lane_ids")]
    pub lane_ids: Vec<i32>,
    /// The ids of the columns which are a part of the merged area.
    #[serde(rename = "column_ids")]
    pub column_ids: Vec<i32>,
    /// The id of the primary column.
    #[serde(rename = "primary_column_id")]
    pub primary_column_id: i32,
    /// The WIP limit of the merged area.
    #[serde(rename = "limit", skip_serializing_if = "Option::is_none")]
    pub limit: Option<i32>,
}

impl CreateMergedAreaRequest {
    /// Merged area data.
    pub fn new(lane_ids: Vec<i32>, column_ids: Vec<i32>, primary_column_id: i32) -> CreateMergedAreaRequest {
        CreateMergedAreaRequest {
            lane_ids,
            column_ids,
            primary_column_id,
            limit: None,
        }
    }
}


