/*
 * Kanbanize API v2
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@kanbanize.com
 * Generated by: https://openapi-generator.tech
 */

/// CreateWebhookRequest : Webhook data.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateWebhookRequest {
    /// The url of the new webhook.
    #[serde(rename = "url")]
    pub url: String,
    /// Controls whether the webhook is enabled or not.
    #[serde(rename = "is_enabled", skip_serializing_if = "Option::is_none")]
    pub is_enabled: Option<IsEnabled>,
    /// An id of a board for the events of which the webhook will be invoked. If not set, the webhook will be invoked for the events of all boards.
    #[serde(rename = "board_id", skip_serializing_if = "Option::is_none")]
    pub board_id: Option<i32>,
}

impl CreateWebhookRequest {
    /// Webhook data.
    pub fn new(url: String) -> CreateWebhookRequest {
        CreateWebhookRequest {
            url,
            is_enabled: None,
            board_id: None,
        }
    }
}

/// Controls whether the webhook is enabled or not.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum IsEnabled {
    #[serde(rename = "0")]
    Variant0,
    #[serde(rename = "1")]
    Variant1,
}

impl Default for IsEnabled {
    fn default() -> IsEnabled {
        Self::Variant0
    }
}

