/*
 * Kanbanize API v2
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@kanbanize.com
 * Generated by: https://openapi-generator.tech
 */

/// GetMyDashboardPageSettings200Response : A wrapper for a successful response.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetMyDashboardPageSettings200Response {
    /// A list of the settings added to one of mine dashboard pages.
    #[serde(rename = "data", skip_serializing_if = "Option::is_none")]
    pub data: Option<Vec<crate::models::GetMyDashboardPageSettings200ResponseDataInner>>,
}

impl GetMyDashboardPageSettings200Response {
    /// A wrapper for a successful response.
    pub fn new() -> GetMyDashboardPageSettings200Response {
        GetMyDashboardPageSettings200Response {
            data: None,
        }
    }
}


