/*
 * Kanbanize API v2
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@kanbanize.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetBlockReasonCards200ResponseDataInner {
    #[serde(rename = "card_id", skip_serializing_if = "Option::is_none")]
    pub card_id: Option<i32>,
}

impl GetBlockReasonCards200ResponseDataInner {
    pub fn new() -> GetBlockReasonCards200ResponseDataInner {
        GetBlockReasonCards200ResponseDataInner {
            card_id: None,
        }
    }
}


