/*
 * Kanbanize API v2
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@kanbanize.com
 * Generated by: https://openapi-generator.tech
 */

/// ParentChildLink : Parent-Child link data



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ParentChildLink {
    #[serde(rename = "parent_id", skip_serializing_if = "Option::is_none")]
    pub parent_id: Option<i32>,
    #[serde(rename = "child_id", skip_serializing_if = "Option::is_none")]
    pub child_id: Option<i32>,
    #[serde(rename = "depth", skip_serializing_if = "Option::is_none")]
    pub depth: Option<i32>,
}

impl ParentChildLink {
    /// Parent-Child link data
    pub fn new() -> ParentChildLink {
        ParentChildLink {
            parent_id: None,
            child_id: None,
            depth: None,
        }
    }
}


