/*
 * Kanbanize API v2
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@kanbanize.com
 * Generated by: https://openapi-generator.tech
 */

/// SetMyBoardSettingRequest : The value of the setting.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SetMyBoardSettingRequest {
    #[serde(rename = "value")]
    pub value: Box<crate::models::SetMyBoardSettingRequestValue>,
}

impl SetMyBoardSettingRequest {
    /// The value of the setting.
    pub fn new(value: crate::models::SetMyBoardSettingRequestValue) -> SetMyBoardSettingRequest {
        SetMyBoardSettingRequest {
            value: Box::new(value),
        }
    }
}


