/*
 * Kanbanize API v2
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@kanbanize.com
 * Generated by: https://openapi-generator.tech
 */

/// SetMySettingsBoardsRequest : Settings boards data.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SetMySettingsBoardsRequest {
    /// A list of board ids where you want to set a list of settings.
    #[serde(rename = "board_ids")]
    pub board_ids: Vec<i32>,
    /// A list of settings whitch you want to set for a list of boards.
    #[serde(rename = "settings")]
    pub settings: Vec<crate::models::SetMySettingsBoardsRequestSettingsInner>,
}

impl SetMySettingsBoardsRequest {
    /// Settings boards data.
    pub fn new(board_ids: Vec<i32>, settings: Vec<crate::models::SetMySettingsBoardsRequestSettingsInner>) -> SetMySettingsBoardsRequest {
        SetMySettingsBoardsRequest {
            board_ids,
            settings,
        }
    }
}


