/*
 * Kanbanize API v2
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@kanbanize.com
 * Generated by: https://openapi-generator.tech
 */

/// TagHistoryEvent : An event recorded when an update, delete or create action is executed on tags resource



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct TagHistoryEvent {
    #[serde(rename = "history_id", skip_serializing_if = "Option::is_none")]
    pub history_id: Option<i32>,
    #[serde(rename = "tag_id", skip_serializing_if = "Option::is_none")]
    pub tag_id: Option<i32>,
    #[serde(rename = "user_id", skip_serializing_if = "Option::is_none")]
    pub user_id: Option<i32>,
    #[serde(rename = "event_type", skip_serializing_if = "Option::is_none")]
    pub event_type: Option<String>,
    #[serde(rename = "details", skip_serializing_if = "Option::is_none")]
    pub details: Option<serde_json::Value>,
    #[serde(rename = "time", skip_serializing_if = "Option::is_none")]
    pub time: Option<String>,
}

impl TagHistoryEvent {
    /// An event recorded when an update, delete or create action is executed on tags resource
    pub fn new() -> TagHistoryEvent {
        TagHistoryEvent {
            history_id: None,
            tag_id: None,
            user_id: None,
            event_type: None,
            details: None,
            time: None,
        }
    }
}


