/*
 * Kanbanize API v2
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@kanbanize.com
 * Generated by: https://openapi-generator.tech
 */

/// UpdateWorkspaceRequest : Workspace data.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateWorkspaceRequest {
    /// The name of the workspace.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Controls whether the workspace is archived or not.
    #[serde(rename = "is_archived", skip_serializing_if = "Option::is_none")]
    pub is_archived: Option<IsArchived>,
}

impl UpdateWorkspaceRequest {
    /// Workspace data.
    pub fn new() -> UpdateWorkspaceRequest {
        UpdateWorkspaceRequest {
            name: None,
            is_archived: None,
        }
    }
}

/// Controls whether the workspace is archived or not.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum IsArchived {
    #[serde(rename = "0")]
    Variant0,
    #[serde(rename = "1")]
    Variant1,
}

impl Default for IsArchived {
    fn default() -> IsArchived {
        Self::Variant0
    }
}

