/*
 * Kanbanize API v2
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@kanbanize.com
 * Generated by: https://openapi-generator.tech
 */

/// UpdateLoggedTimeRequest : Card logged time data.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateLoggedTimeRequest {
    /// The id of the card for which the time is logged.
    #[serde(rename = "card_id", skip_serializing_if = "Option::is_none")]
    pub card_id: Option<i32>,
    /// If the logged time is for a subtask, the id of the subtask for which the time is logged. If the logged time is for a card, this field can be skipped or a null value can be sent.
    #[serde(rename = "subtask_id", skip_serializing_if = "Option::is_none")]
    pub subtask_id: Option<i32>,
    /// The id of the lane in which we want the logged time to appear.
    #[serde(rename = "lane_id", skip_serializing_if = "Option::is_none")]
    pub lane_id: Option<i32>,
    /// The id of the column in which we want the logged time to appear.
    #[serde(rename = "column_id", skip_serializing_if = "Option::is_none")]
    pub column_id: Option<i32>,
    /// The id of the user for whom the time is logged.
    #[serde(rename = "user_id", skip_serializing_if = "Option::is_none")]
    pub user_id: Option<i32>,
    /// The date for which the time is logged.
    #[serde(rename = "date", skip_serializing_if = "Option::is_none")]
    pub date: Option<String>,
    /// The amount of time to log in seconds.
    #[serde(rename = "time", skip_serializing_if = "Option::is_none")]
    pub time: Option<i32>,
    /// An optional comment.
    #[serde(rename = "comment", skip_serializing_if = "Option::is_none")]
    pub comment: Option<String>,
}

impl UpdateLoggedTimeRequest {
    /// Card logged time data.
    pub fn new() -> UpdateLoggedTimeRequest {
        UpdateLoggedTimeRequest {
            card_id: None,
            subtask_id: None,
            lane_id: None,
            column_id: None,
            user_id: None,
            date: None,
            time: None,
            comment: None,
        }
    }
}


