/*
 * Kanbanize API v2
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@kanbanize.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateCustomFieldBoards200ResponseData {
}

impl UpdateCustomFieldBoards200ResponseData {
    pub fn new() -> UpdateCustomFieldBoards200ResponseData {
        UpdateCustomFieldBoards200ResponseData {
        }
    }
}


