/*
 * Kanbanize API v2
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@kanbanize.com
 * Generated by: https://openapi-generator.tech
 */

/// UpdateMyCardCustomFieldVote200Response : Card custom field vote data.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateMyCardCustomFieldVote200Response {
    #[serde(rename = "data", skip_serializing_if = "Option::is_none")]
    pub data: Option<Box<crate::models::UpdateMyCardCustomFieldVote200ResponseData>>,
}

impl UpdateMyCardCustomFieldVote200Response {
    /// Card custom field vote data.
    pub fn new() -> UpdateMyCardCustomFieldVote200Response {
        UpdateMyCardCustomFieldVote200Response {
            data: None,
        }
    }
}


