/*
 * Kanbanize API v2
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@kanbanize.com
 * Generated by: https://openapi-generator.tech
 */

/// UpdateRoleRequest : Role data.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateRoleRequest {
    /// The name of the new role.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
}

impl UpdateRoleRequest {
    /// Role data.
    pub fn new() -> UpdateRoleRequest {
        UpdateRoleRequest {
            name: None,
        }
    }
}


